[book]
title = "Cardano-Monero Atomic Swap Protocol"
authors = ["Atomic Swap Tutorial"]
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "book"
create-missing = true

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/Unisay/atomic-swap-adapter-sigs"
edit-url-template = "https://github.com/Unisay/atomic-swap-adapter-sigs/edit/main/doc/{path}"

[output.html.fold]
enable = true
level = 1

[output.html.search]
enable = true
